### ISSUE TITLE
page, note, owner, book and ticket?

### ISSUE THREAD

**Issue by otsl0110** [NeoSmartpen/NcodeSDK#2]
Let me ask a question here.
I'd like to clarify relations of IDs.
I heard 1 ticket contain 1024 pages max, is that right? or Should I say 1 file can contain 1024 tickets(pages)?

I also heard 1 file can be divided into books. how many pages in 1 book and how many books in a ticket file?

From pen stroke we obtain page id, note id, and owner id also. Are those associate to 1 ticket? or 1 file? or page by page?

I appreciate your prompt reply.  Thank you.

**Comment by hrhwang** [comment]
One ticket can have up to 8192 books.
And one book can have up to 512 pages.
However, since the minimum contract unit is 1024 pages, when the contract is concluded, 2 books with the 512 pages will be given.
The information you can get from the Pen is page information of the printed Ncode regardless of the ticket (owner ID, note ID, page ID, x pos, y pos)

**Comment by otsl0110** [comment]
Thank you for your reply.
Who provides owner ID and note ID?  Is that up to licensee? means, those are managed by author?

**Comment by otsl0110** [comment]
Please also reply to me about other questions.

1. Origin of stroke data?
2. Unit of stroke data?

Thank you.

**Comment by hrhwang** [comment]
You'd better contact the **NeoLAB pen SDK** for data coming from the pen.
If your company has a good understanding of our technology and agrees with our overseas business team, we can issue you an account.
I will inform you again at that time about the information you need to issue your account.

**Comment by otsl0110** [comment]
Yes,　I had placed pen data question to SDK git, but so far no reply yet.
Thank you for your reply.

**Comment by sreyansh57** [comment]
I need more paper in PDF
Please someone help me out.

It's very urgent

Sreyansh

**Comment by hrhwang** [comment]
Are you developing a prototype using the sample appkey?
I do not know what the situation is.
Please tell me more.

**Comment by sreyansh57** [comment]
Yes we are developing a product using nasdk android sdk  for pen
 Currently we are using sample 50 pages available on website.
 We would be requiring more unique pages to move ahead.
Please let me know of way ahead.

Thanks

Sreyansh

On Jun 26, 2017 12:52 PM, "hrhwang" <notifications@github.com> wrote:

Are you developing a prototype using the sample appkey?
I do not know what the situation is.
Please tell me more.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NeoSmartpen/NcodeSDK/issues/2#issuecomment-310982460>,
or mute the thread

**Comment by hrhwang** [comment]
The Ncode SDK supports about 5000 pages of Ncode through the sample appkey.
I think your inquiry is not about NcodeSDK.
Are you using five types of note pdf files that you can download from the homepage?
If so, there is no other way to use another type of note pdf file.
The files only support 50 pages for each type, but do not support additional pages.

**Comment by sreyansh57** [comment]
Yes we are developing a product using nasdk android sdk  for pen
 Currently we are using sample 50 pages available on website.
 We would be requiring more unique pages to move ahead.
Please let me know of way ahead.
waiting for your response.

Thanks

Sreyansh

**Comment by sreyansh57** [comment]
The Ncode SDK supports about 5000 pages of Ncode through the sample appkey.
I think your inquiry is not about NcodeSDK.

what does it mean?

we have got 50 pages from website andutilised all.

please guide how i can get more unique pages.

Thanks

sreyansh

**Comment by hrhwang** [comment]
The sample pdf file is no longer extended.
If you need more unique pages for your application, you should contract with our business team and download Ncode via the Ncode SDK.
For inquiries about contracts, please contact (hjhwang@neolab.net)

**Comment by PriyankGadhiya** [comment]
Let me ask a question here.
I'd like to clarify for books.

i have to one ticket 
I'll be printing 600 pages times in a while then i'll face the Error 

![capture](https://user-images.githubusercontent.com/44332568/51227237-6489cb00-1979-11e9-8c39-2836f3337c91.PNG)

How do I print the 600 page for my book? in one time 

Please someone help me out.
It's very urgent...
